In [1]:
import numpy as np

## DataTypes and Attributes

In [2]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a1.ndim

1

In [6]:
a2 = np.array([[1,2,3], [4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
a2.ndim

2

In [8]:
a3 = np.array([[[1,2,3],[3,4,5]],[[6,7,8], [9,10,11]]])
a3

array([[[ 1,  2,  3],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [27]:
a3.shape

(2, 2, 3)

In [9]:
a3.ndim

3

In [10]:
import pandas as pd

In [12]:
pd.DataFrame(a2)

0  1  2
0  1  2  3
1  4  5  6

In [13]:
zeros = np.zeros((2,3))

In [14]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
zeros.size

6

In [16]:
zeros.shape

(2, 3)

## np.random.seed()

In [25]:
random1 = np.random.random((5,2))
random1

array([[0.13316945, 0.52341258],
       [0.75040986, 0.66901324],
       [0.46775286, 0.20484909],
       [0.49076589, 0.37238469],
       [0.47740115, 0.36589039]])

In [26]:
np.random.seed(7)
random2 = np.random.random((5,3))
random2

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

## STD and VAR

In [40]:
times = np.array([1,1, 60, 60, 90, 90, 90, 120, 120, 120, 180, 240, 5000])

In [41]:
np.var(times)

1710340.4852071006

In [42]:
np.mean(times)

474.7692307692308

In [43]:
np.std(times)

1307.7998643550552

In [44]:
np.median(times)

90.0

In [45]:
from scipy import stats
m = stats.mode(times)
m

ModeResult(mode=90, count=3)

## Dot product

In [46]:
np.random.seed(0)
sales = np.random.randint(20, size=(5,3))
sales

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [47]:
sales_df = pd.DataFrame(sales)

In [48]:
sales_df

0   1   2
0  12  15   0
1   3   3   7
2   9  19  18
3   4   6  12
4   1   6   7

In [49]:
prices = np.array([10, 8, 12])

In [50]:
prices.shape

(3,)

In [51]:
prices.T

array([10,  8, 12])

In [52]:
prices.shape

(3,)

In [53]:
prices.reshape

<function ndarray.reshape>

In [54]:
prices.shape

(3,)

In [55]:
sales.T
sales.shape

(5, 3)

In [56]:
np.dot(sales, prices)

array([240, 138, 458, 232, 142])

## Images to array

In [57]:
from matplotlib.image import imread

In [58]:
img = imread('Gemini_Generated_Image.jpeg')

In [59]:
img

array([[[126, 142,  97],
        [129, 142,  96],
        [117, 130,  84],
        ...,
        [103, 119,  72],
        [ 93, 105,  67],
        [ 52,  63,  29]],

       [[ 92, 108,  63],
        [ 85, 101,  56],
        [ 56,  69,  25],
        ...,
        [ 95, 112,  67],
        [ 72,  84,  46],
        [ 44,  55,  21]],

       [[ 56,  71,  30],
        [ 71,  86,  45],
        [ 45,  60,  19],
        ...,
        [ 72,  87,  46],
        [ 55,  66,  32],
        [ 43,  54,  22]],

       ...,

       [[ 42,  39,  24],
        [ 39,  36,  21],
        [ 43,  40,  25],
        ...,
        [ 26,  37,  33],
        [ 28,  39,  35],
        [ 30,  41,  35]],

       [[ 40,  37,  22],
        [ 46,  43,  28],
        [ 46,  42,  30],
        ...,
        [ 25,  37,  33],
        [ 28,  40,  36],
        [ 31,  44,  37]],

       [[ 47,  44,  29],
        [ 59,  56,  41],
        [ 57,  53,  41],
        ...,
        [ 26,  38,  34],
        [ 29,  41,  37],
        [ 33,  46,  39]]

In [60]:
type(img)

numpy.ndarray

In [61]:
img.shape

(1536, 1536, 3)